### ISSUE TITLE
feat: follow a space

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#282]
For Snapshot spaces only, we should replace favorite icon on space overview with a button "Follow" like this:
<img width="1455" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/54528553-faa8-4abc-9e3c-05befd395481">
When followed, the label should be "Following" like this:
<img width="365" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/1ae25b27-25ce-4c6b-84f9-e331f1115d5f">
On mouse over if already followed, it should show "Unfollow" in red like this:
<img width="388" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/f3d225a3-c323-4f7f-81fd-f7836f916d55">

Instead of adding the space in the localStorage like favorite, it should send an action to Snapshot sequencer to do a follow. This require session key, or "alias". This is something we do on Snapshot, when someone try to follow a space for the first time, we generate an Ethereum private key and store it in local storage with a corresponding logged user address, then we sign a message from the logged wallet to give authority to the session key to be used to do action like follow. Then we can do a follow action with the session key (signing in the browser without going through the wallet). The session key should only be created when needed (on first follow), we don't want to have signing wall on user arrival.

We should also display the followed spaces on the very left sidebar, (along with favorites)
<img width="123" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/3d5c2cdb-0e60-4f4b-b8e8-825c030d4b5a">
This can be done in a separated PR.

```[tasklist]
### Tasks
- [x] Load an account's follows list from the hub (done via #217)
- [x] Show followed spaces in the sidebar #288
- [x] Replace "favorite" by "follows/unfollows" in v1 space #288
- [x] Send follow/unfollow actions to the sequencer https://github.com/snapshot-labs/sx-monorepo/pull/293
- [ ] Implement alias system for voting without signature
```

**Comment by wa0x6e** [comment]
Should we extract the session key in another PR, or keep in this one ?

And do starknet address can also follow snapshot space, or do we restrict it to only EVM address ?

**Comment by bonustrack** [comment]
The more we separate the better is it IMO. And we should not support SX spaces or Starknet wallet.

**Comment by wa0x6e** [comment]
So we should disable following for users logged in with starknet wallet ? Just disable or fallback to favorite like now ?

**Comment by bonustrack** [comment]
We can remove the button for Starknet user on Snapshot space

**Comment by wa0x6e** [comment]
Do we also add followed spaces in the sidebar ?

**Comment by bonustrack** [comment]
Yes
