### ISSUE TITLE
refactor: refactor component naming & structure

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/sx-monorepo#5]
Pitch https://www.notion.so/snapshotlabs/SX-UI-component-naming-structure-46b4270e9e254678a5d8dce74582fb37?pvs=4

```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/sx-monorepo/issues/8
- [ ] https://github.com/snapshot-labs/sx-monorepo/issues/9
- [ ] https://github.com/snapshot-labs/sx-monorepo/issues/6
- [ ] https://github.com/snapshot-labs/sx-monorepo/issues/10
- [ ] https://github.com/snapshot-labs/sx-monorepo/issues/33
```

**Comment by Sekhmet** [comment]
@samuveth can we consider it done?
