### ISSUE TITLE
refactor: move away from single voting power composable/store

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/sx-monorepo#939]
```[tasklist]
### Tasks
- [ ] https://github.com/snapshot-labs/sx-monorepo/pull/938
- [x] refactor: create dedicated composable for propose voting power
- [x] refactor: create dedicated store for vote voting power
- [x] refactor: create dedicated store for propose voting power
```
